name: gosheep_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.0.0
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  dio: ^5.9.2
  shimmer: ^3.0.0
  flutter_svg: ^2.2.4
  dropdown_search: ^7.0.0
  fl_chart: ^0.68.0
  google_mlkit_text_recognition: ^0.15.1
  camera: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Konfigurasi launcher icons ditaruh di level paling luar/bawah
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/goSheep_logo.png"
  remove_alpha_ios: true
